---
version: '3'

services:
  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.web.address=:81"
    ports:
      - "81:81"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # - "./traefik.toml:/etc/traefik/traefik.toml"
      # - "./traefik.yaml/:/etc/traefik/traefik.yaml"

  api:
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.api.rule=PathPrefix(`/api`)
    image: sp33c/python:3.8
    ports:
      - 8000:8000
    container_name: api
    volumes:
      - .:/work
    command: "./rc/production-volume.sh"

  postgres:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_PASSWORD=dbpasswd
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=appdb
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - .:/var/lib/postgresql/data
    container_name: postgres

  pgadmin:
    image: dpage/pgadmin4
    labels:
      - "traefik.enable=true"
      # - "traefik.http.routers.pgadmin.rule=PathPrefix(`/pgadmin`)"
      # - "traefik.http.middlewares.pgadmin.stripprefix.prefixes=/pgadmin"
      # - "traefik.http.middlewares.pgadmin.stripprefix.forceslash=false"
    environment:
      - PGADMIN_DEFAULT_EMAIL=info@sp33c.tech
      - PGADMIN_DEFAULT_PASSWORD=prinus
      # - SCRIPT_NAME=/pgadmin
    volumes:
      - ./etc/servers.json:/pgadmin4/servers.json
    ports:
      - 8082:80
    container_name: pgadmin
