---
version: '3'

services:
  api:
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.api.rule=PathPrefix(`/api`)
    image: 127.0.0.1:5001/api:1.0
    build: .
    ports:
      - 8000:8000
    deploy:
      placement:
        constraints:
          - node.labels.worker==python
      replicas: 4
      update_config:
        parallelism: 2
        delay: 10s

  postgres:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_PASSWORD=dbpasswd
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=appdb
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - .:/var/lib/postgresql/data
    deploy: 
      placement: 
        constraints:
          - node.labels.role==db
            #- node.role == manager

  pgadmin:
    image: dpage/pgadmin4
    labels:
      - "traefik.enable=true"
      # - "traefik.http.routers.pgadmin.rule=PathPrefix(`/pgadmin`)"
      # - "traefik.http.middlewares.pgadmin.stripprefix.prefixes=/pgadmin"
      # - "traefik.http.middlewares.pgadmin.stripprefix.forceslash=false"
    environment:
      - PGADMIN_DEFAULT_EMAIL=info@sp33c.tech
      - PGADMIN_DEFAULT_PASSWORD=prinus
      # - SCRIPT_NAME=/pgadmin
    volumes:
      - ./etc/servers.json:/pgadmin4/servers.json
    ports:
      - 8082:80
    deploy:
      placement:
        constraints:
          - node.labels.role==db
                #- node.role == manager
