version: '3'

services:
#  api:
#    image: sp33c/python:3.7
#    ports:
#      - 8080:5000
#    container_name: api
#    volumes:
#      - .:/app
#    command: zsh
#    #"./production.sh"

  redis:
    container_name: redis
    hostname: redis
    image: redis

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8085:8081"

  postgres:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_PASSWORD=dbpasswd
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=appdb
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - .:/var/lib/postgresql/data
    container_name: postgres
#    ports:
      #- 5432:5432
#    networks:
#      - vps1

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=info@sp33c.tech
      - PGADMIN_DEFAULT_PASSWORD=prinus
    volumes:
      - ./etc/servers.json:/pgadmin4/servers.json
    ports: 
      - 8081:80
    container_name: pgadmin

#volumes:
#  pgdata:

